#!/usr/bin/env bash

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"

rm -rf ./pkg/pb
mkdir -p ./pkg/pb

protoc --go_out=./pkg/pb --go_opt=paths=source_relative --go-grpc_out=./pkg/pb --go-grpc_opt=paths=source_relative $(find ./proto -iname "*.proto") --proto_path=./proto
