#!/usr/bin/env bash

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"

TARGET=./common/pb

rm -rf $TARGET
mkdir -p $TARGET

protoc --go_out=$TARGET --go_opt=paths=source_relative --go-grpc_out=$TARGET --go-grpc_opt=paths=source_relative $(find ./proto -iname "*.proto") --proto_path=./proto
