// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/dorm-parcel-manager/dpm/common/client"
	"github.com/dorm-parcel-manager/dpm/common/pb"
	"github.com/dorm-parcel-manager/dpm/common/server"
	"github.com/dorm-parcel-manager/dpm/services/parcel/config"
	"github.com/dorm-parcel-manager/dpm/services/parcel/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, func(), error) {
	configConfig := config.ProvideConfig()
	serverConfig := configConfig.Server
	clientConfig := configConfig.Client
	userServiceClient, cleanup, err := client.ProvideUserServiceClient(clientConfig)
	if err != nil {
		return nil, nil, err
	}
	parcelServiceServer, err := service.NewParcelServiceServer(userServiceClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := ProvideGrpcServer(parcelServiceServer)
	serverServer := server.NewServer(serverConfig, grpcServer)
	return serverServer, func() {
		cleanup()
	}, nil
}

// wire.go:

func ProvideGrpcServer(parcelService pb.ParcelServiceServer) *grpc.Server {
	s := grpc.NewServer()
	pb.RegisterParcelServiceServer(s, parcelService)
	return s
}
