// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: parcel-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParcelStatus int32

const (
	ParcelStatus_PARCEL_INAWAIT               ParcelStatus = 0
	ParcelStatus_PARCEL_ACCEPTED              ParcelStatus = 1
	ParcelStatus_PARCEL_STUDENT_CLAIMED       ParcelStatus = 2
	ParcelStatus_PARCEL_STAFF_CONFIRM_CLAIMED ParcelStatus = 3
)

// Enum value maps for ParcelStatus.
var (
	ParcelStatus_name = map[int32]string{
		0: "PARCEL_INAWAIT",
		1: "PARCEL_ACCEPTED",
		2: "PARCEL_STUDENT_CLAIMED",
		3: "PARCEL_STAFF_CONFIRM_CLAIMED",
	}
	ParcelStatus_value = map[string]int32{
		"PARCEL_INAWAIT":               0,
		"PARCEL_ACCEPTED":              1,
		"PARCEL_STUDENT_CLAIMED":       2,
		"PARCEL_STAFF_CONFIRM_CLAIMED": 3,
	}
)

func (x ParcelStatus) Enum() *ParcelStatus {
	p := new(ParcelStatus)
	*p = x
	return p
}

func (x ParcelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParcelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_parcel_service_proto_enumTypes[0].Descriptor()
}

func (ParcelStatus) Type() protoreflect.EnumType {
	return &file_parcel_service_proto_enumTypes[0]
}

func (x ParcelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParcelStatus.Descriptor instead.
func (ParcelStatus) EnumDescriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{0}
}

type Parcel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId          int32                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ArrivalDate      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=arrival_date,json=arrivalDate,proto3" json:"arrival_date,omitempty"`
	TransportCompany string                 `protobuf:"bytes,4,opt,name=transport_company,json=transportCompany,proto3" json:"transport_company,omitempty"`
	TrackingNumber   string                 `protobuf:"bytes,5,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Sender           string                 `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Status           ParcelStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=pb.ParcelStatus" json:"status,omitempty"`
}

func (x *Parcel) Reset() {
	*x = Parcel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parcel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parcel) ProtoMessage() {}

func (x *Parcel) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parcel.ProtoReflect.Descriptor instead.
func (*Parcel) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{0}
}

func (x *Parcel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Parcel) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Parcel) GetArrivalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalDate
	}
	return nil
}

func (x *Parcel) GetTransportCompany() string {
	if x != nil {
		return x.TransportCompany
	}
	return ""
}

func (x *Parcel) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Parcel) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Parcel) GetStatus() ParcelStatus {
	if x != nil {
		return x.Status
	}
	return ParcelStatus_PARCEL_INAWAIT
}

type StudentGetParcelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudentGetParcelsRequest) Reset() {
	*x = StudentGetParcelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentGetParcelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGetParcelsRequest) ProtoMessage() {}

func (x *StudentGetParcelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGetParcelsRequest.ProtoReflect.Descriptor instead.
func (*StudentGetParcelsRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{1}
}

func (x *StudentGetParcelsRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StudentGetParcelsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudentGetParcelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parcels []*Parcel `protobuf:"bytes,1,rep,name=parcels,proto3" json:"parcels,omitempty"`
}

func (x *StudentGetParcelsResponse) Reset() {
	*x = StudentGetParcelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentGetParcelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGetParcelsResponse) ProtoMessage() {}

func (x *StudentGetParcelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGetParcelsResponse.ProtoReflect.Descriptor instead.
func (*StudentGetParcelsResponse) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{2}
}

func (x *StudentGetParcelsResponse) GetParcels() []*Parcel {
	if x != nil {
		return x.Parcels
	}
	return nil
}

type GetParcelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *GetParcelsRequest) Reset() {
	*x = GetParcelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParcelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelsRequest) ProtoMessage() {}

func (x *GetParcelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelsRequest.ProtoReflect.Descriptor instead.
func (*GetParcelsRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetParcelsRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetParcelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parcels []*Parcel `protobuf:"bytes,1,rep,name=parcels,proto3" json:"parcels,omitempty"`
}

func (x *GetParcelsResponse) Reset() {
	*x = GetParcelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParcelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelsResponse) ProtoMessage() {}

func (x *GetParcelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelsResponse.ProtoReflect.Descriptor instead.
func (*GetParcelsResponse) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetParcelsResponse) GetParcels() []*Parcel {
	if x != nil {
		return x.Parcels
	}
	return nil
}

type GetParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetParcelRequest) Reset() {
	*x = GetParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelRequest) ProtoMessage() {}

func (x *GetParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelRequest.ProtoReflect.Descriptor instead.
func (*GetParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetParcelRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetParcelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parcel *Parcel `protobuf:"bytes,1,opt,name=parcel,proto3" json:"parcel,omitempty"`
}

func (x *GetParcelResponse) Reset() {
	*x = GetParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelResponse) ProtoMessage() {}

func (x *GetParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelResponse.ProtoReflect.Descriptor instead.
func (*GetParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetParcelResponse) GetParcel() *Parcel {
	if x != nil {
		return x.Parcel
	}
	return nil
}

type CreateParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context          `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Data    *CreateParcelData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateParcelRequest) Reset() {
	*x = CreateParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelRequest) ProtoMessage() {}

func (x *CreateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelRequest.ProtoReflect.Descriptor instead.
func (*CreateParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateParcelRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateParcelRequest) GetData() *CreateParcelData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateParcelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId          int32  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TransportCompany string `protobuf:"bytes,3,opt,name=transport_company,json=transportCompany,proto3" json:"transport_company,omitempty"`
	TrackingNumber   string `protobuf:"bytes,4,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Sender           string `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *CreateParcelData) Reset() {
	*x = CreateParcelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParcelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelData) ProtoMessage() {}

func (x *CreateParcelData) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelData.ProtoReflect.Descriptor instead.
func (*CreateParcelData) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateParcelData) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateParcelData) GetTransportCompany() string {
	if x != nil {
		return x.TransportCompany
	}
	return ""
}

func (x *CreateParcelData) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateParcelData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type UpdateParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context          `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data    *UpdateParcelData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateParcelRequest) Reset() {
	*x = UpdateParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelRequest) ProtoMessage() {}

func (x *UpdateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelRequest.ProtoReflect.Descriptor instead.
func (*UpdateParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateParcelRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateParcelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateParcelRequest) GetData() *UpdateParcelData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateParcelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId          int32                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ArrivalDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=arrival_date,json=arrivalDate,proto3" json:"arrival_date,omitempty"`
	TransportCompany string                 `protobuf:"bytes,3,opt,name=transport_company,json=transportCompany,proto3" json:"transport_company,omitempty"`
	TrackingNumber   string                 `protobuf:"bytes,4,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Sender           string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Status           ParcelStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=pb.ParcelStatus" json:"status,omitempty"`
}

func (x *UpdateParcelData) Reset() {
	*x = UpdateParcelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParcelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelData) ProtoMessage() {}

func (x *UpdateParcelData) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelData.ProtoReflect.Descriptor instead.
func (*UpdateParcelData) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateParcelData) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *UpdateParcelData) GetArrivalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalDate
	}
	return nil
}

func (x *UpdateParcelData) GetTransportCompany() string {
	if x != nil {
		return x.TransportCompany
	}
	return ""
}

func (x *UpdateParcelData) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *UpdateParcelData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *UpdateParcelData) GetStatus() ParcelStatus {
	if x != nil {
		return x.Status
	}
	return ParcelStatus_PARCEL_INAWAIT
}

type DeleteParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteParcelRequest) Reset() {
	*x = DeleteParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParcelRequest) ProtoMessage() {}

func (x *DeleteParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParcelRequest.ProtoReflect.Descriptor instead.
func (*DeleteParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteParcelRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteParcelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StaffAcceptDeliveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StaffAcceptDeliveryRequest) Reset() {
	*x = StaffAcceptDeliveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffAcceptDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffAcceptDeliveryRequest) ProtoMessage() {}

func (x *StaffAcceptDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffAcceptDeliveryRequest.ProtoReflect.Descriptor instead.
func (*StaffAcceptDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{12}
}

func (x *StaffAcceptDeliveryRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StaffAcceptDeliveryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudentClaimParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudentClaimParcelRequest) Reset() {
	*x = StudentClaimParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentClaimParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClaimParcelRequest) ProtoMessage() {}

func (x *StudentClaimParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClaimParcelRequest.ProtoReflect.Descriptor instead.
func (*StudentClaimParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{13}
}

func (x *StudentClaimParcelRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StudentClaimParcelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StaffConfirmClaimParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id      uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StaffConfirmClaimParcelRequest) Reset() {
	*x = StaffConfirmClaimParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffConfirmClaimParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffConfirmClaimParcelRequest) ProtoMessage() {}

func (x *StaffConfirmClaimParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffConfirmClaimParcelRequest.ProtoReflect.Descriptor instead.
func (*StaffConfirmClaimParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_service_proto_rawDescGZIP(), []int{14}
}

func (x *StaffConfirmClaimParcelRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StaffConfirmClaimParcelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_parcel_service_proto protoreflect.FileDescriptor

var file_parcel_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x06, 0x50, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x3d, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x18, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x19, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x52, 0x07, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x22, 0x3a, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x07, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x07, 0x70, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x73, 0x22, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x22, 0x66, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x9b, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a,
	0x0f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x76,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x84, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61,
	0x6c, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61,
	0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4c, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x1a, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x52, 0x0a, 0x19, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x1e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x75, 0x0a,
	0x0c, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x0e, 0x50, 0x41, 0x52, 0x43, 0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x41, 0x57, 0x41, 0x49, 0x54, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x52, 0x43, 0x45, 0x4c, 0x5f, 0x41, 0x43, 0x43, 0x45,
	0x50, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x52, 0x43, 0x45, 0x4c,
	0x5f, 0x53, 0x54, 0x55, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x50, 0x41, 0x52, 0x43, 0x45, 0x4c, 0x5f, 0x53, 0x54, 0x41,
	0x46, 0x46, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x5f, 0x43, 0x4c, 0x41, 0x49, 0x4d,
	0x45, 0x44, 0x10, 0x03, 0x32, 0x81, 0x05, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x11, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x34, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x1e,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x12, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x16, 0x53, 0x74, 0x61, 0x66, 0x66, 0x6f, 0x6d, 0x66, 0x69, 0x72, 0x6d, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x72, 0x6d, 0x2d, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x64, 0x70, 0x6d, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parcel_service_proto_rawDescOnce sync.Once
	file_parcel_service_proto_rawDescData = file_parcel_service_proto_rawDesc
)

func file_parcel_service_proto_rawDescGZIP() []byte {
	file_parcel_service_proto_rawDescOnce.Do(func() {
		file_parcel_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_parcel_service_proto_rawDescData)
	})
	return file_parcel_service_proto_rawDescData
}

var file_parcel_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_parcel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_parcel_service_proto_goTypes = []interface{}{
	(ParcelStatus)(0),                      // 0: pb.ParcelStatus
	(*Parcel)(nil),                         // 1: pb.Parcel
	(*StudentGetParcelsRequest)(nil),       // 2: pb.StudentGetParcelsRequest
	(*StudentGetParcelsResponse)(nil),      // 3: pb.StudentGetParcelsResponse
	(*GetParcelsRequest)(nil),              // 4: pb.GetParcelsRequest
	(*GetParcelsResponse)(nil),             // 5: pb.GetParcelsResponse
	(*GetParcelRequest)(nil),               // 6: pb.GetParcelRequest
	(*GetParcelResponse)(nil),              // 7: pb.GetParcelResponse
	(*CreateParcelRequest)(nil),            // 8: pb.CreateParcelRequest
	(*CreateParcelData)(nil),               // 9: pb.CreateParcelData
	(*UpdateParcelRequest)(nil),            // 10: pb.UpdateParcelRequest
	(*UpdateParcelData)(nil),               // 11: pb.UpdateParcelData
	(*DeleteParcelRequest)(nil),            // 12: pb.DeleteParcelRequest
	(*StaffAcceptDeliveryRequest)(nil),     // 13: pb.StaffAcceptDeliveryRequest
	(*StudentClaimParcelRequest)(nil),      // 14: pb.StudentClaimParcelRequest
	(*StaffConfirmClaimParcelRequest)(nil), // 15: pb.StaffConfirmClaimParcelRequest
	(*timestamppb.Timestamp)(nil),          // 16: google.protobuf.Timestamp
	(*Context)(nil),                        // 17: pb.Context
	(*HelloRequest)(nil),                   // 18: pb.HelloRequest
	(*HelloResponse)(nil),                  // 19: pb.HelloResponse
	(*Empty)(nil),                          // 20: pb.Empty
}
var file_parcel_service_proto_depIdxs = []int32{
	16, // 0: pb.Parcel.arrival_date:type_name -> google.protobuf.Timestamp
	0,  // 1: pb.Parcel.status:type_name -> pb.ParcelStatus
	17, // 2: pb.StudentGetParcelsRequest.context:type_name -> pb.Context
	1,  // 3: pb.StudentGetParcelsResponse.parcels:type_name -> pb.Parcel
	17, // 4: pb.GetParcelsRequest.context:type_name -> pb.Context
	1,  // 5: pb.GetParcelsResponse.parcels:type_name -> pb.Parcel
	17, // 6: pb.GetParcelRequest.context:type_name -> pb.Context
	1,  // 7: pb.GetParcelResponse.parcel:type_name -> pb.Parcel
	17, // 8: pb.CreateParcelRequest.context:type_name -> pb.Context
	9,  // 9: pb.CreateParcelRequest.data:type_name -> pb.CreateParcelData
	17, // 10: pb.UpdateParcelRequest.context:type_name -> pb.Context
	11, // 11: pb.UpdateParcelRequest.data:type_name -> pb.UpdateParcelData
	16, // 12: pb.UpdateParcelData.arrival_date:type_name -> google.protobuf.Timestamp
	0,  // 13: pb.UpdateParcelData.status:type_name -> pb.ParcelStatus
	17, // 14: pb.DeleteParcelRequest.context:type_name -> pb.Context
	17, // 15: pb.StaffAcceptDeliveryRequest.context:type_name -> pb.Context
	17, // 16: pb.StudentClaimParcelRequest.context:type_name -> pb.Context
	17, // 17: pb.StaffConfirmClaimParcelRequest.context:type_name -> pb.Context
	18, // 18: pb.ParcelService.Hello:input_type -> pb.HelloRequest
	4,  // 19: pb.ParcelService.GetParcels:input_type -> pb.GetParcelsRequest
	2,  // 20: pb.ParcelService.StudentGetParcels:input_type -> pb.StudentGetParcelsRequest
	6,  // 21: pb.ParcelService.GetParcel:input_type -> pb.GetParcelRequest
	8,  // 22: pb.ParcelService.CreateParcel:input_type -> pb.CreateParcelRequest
	10, // 23: pb.ParcelService.UpdateParcel:input_type -> pb.UpdateParcelRequest
	12, // 24: pb.ParcelService.DeleteParcel:input_type -> pb.DeleteParcelRequest
	13, // 25: pb.ParcelService.StaffAcceptDelivery:input_type -> pb.StaffAcceptDeliveryRequest
	14, // 26: pb.ParcelService.StudentClaimParcel:input_type -> pb.StudentClaimParcelRequest
	15, // 27: pb.ParcelService.StaffomfirmClaimParcel:input_type -> pb.StaffConfirmClaimParcelRequest
	19, // 28: pb.ParcelService.Hello:output_type -> pb.HelloResponse
	5,  // 29: pb.ParcelService.GetParcels:output_type -> pb.GetParcelsResponse
	3,  // 30: pb.ParcelService.StudentGetParcels:output_type -> pb.StudentGetParcelsResponse
	7,  // 31: pb.ParcelService.GetParcel:output_type -> pb.GetParcelResponse
	20, // 32: pb.ParcelService.CreateParcel:output_type -> pb.Empty
	20, // 33: pb.ParcelService.UpdateParcel:output_type -> pb.Empty
	20, // 34: pb.ParcelService.DeleteParcel:output_type -> pb.Empty
	20, // 35: pb.ParcelService.StaffAcceptDelivery:output_type -> pb.Empty
	20, // 36: pb.ParcelService.StudentClaimParcel:output_type -> pb.Empty
	20, // 37: pb.ParcelService.StaffomfirmClaimParcel:output_type -> pb.Empty
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_parcel_service_proto_init() }
func file_parcel_service_proto_init() {
	if File_parcel_service_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_parcel_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parcel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentGetParcelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentGetParcelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParcelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParcelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParcelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParcelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffAcceptDeliveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentClaimParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffConfirmClaimParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parcel_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parcel_service_proto_goTypes,
		DependencyIndexes: file_parcel_service_proto_depIdxs,
		EnumInfos:         file_parcel_service_proto_enumTypes,
		MessageInfos:      file_parcel_service_proto_msgTypes,
	}.Build()
	File_parcel_service_proto = out.File
	file_parcel_service_proto_rawDesc = nil
	file_parcel_service_proto_goTypes = nil
	file_parcel_service_proto_depIdxs = nil
}
