// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: parcel-service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParcelServiceClient is the client API for ParcelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParcelServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type parcelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParcelServiceClient(cc grpc.ClientConnInterface) ParcelServiceClient {
	return &parcelServiceClient{cc}
}

func (c *parcelServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/pb.ParcelService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParcelServiceServer is the server API for ParcelService service.
// All implementations must embed UnimplementedParcelServiceServer
// for forward compatibility
type ParcelServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedParcelServiceServer()
}

// UnimplementedParcelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedParcelServiceServer struct {
}

func (UnimplementedParcelServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedParcelServiceServer) mustEmbedUnimplementedParcelServiceServer() {}

// UnsafeParcelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParcelServiceServer will
// result in compilation errors.
type UnsafeParcelServiceServer interface {
	mustEmbedUnimplementedParcelServiceServer()
}

func RegisterParcelServiceServer(s grpc.ServiceRegistrar, srv ParcelServiceServer) {
	s.RegisterService(&ParcelService_ServiceDesc, srv)
}

func _ParcelService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ParcelService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParcelService_ServiceDesc is the grpc.ServiceDesc for ParcelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParcelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ParcelService",
	HandlerType: (*ParcelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _ParcelService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parcel-service.proto",
}
