// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/dorm-parcel-manager/dpm/pkg/parcel/config"
	"github.com/dorm-parcel-manager/dpm/pkg/parcel/service"
	"github.com/dorm-parcel-manager/dpm/pkg/pb"
	"github.com/dorm-parcel-manager/dpm/pkg/server"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig := config.ProvideConfig()
	serverConfig := configConfig.Server
	parcelServiceServer, err := service.NewParcelServiceServer()
	if err != nil {
		return nil, err
	}
	grpcServer := ProvideGrpcServer(parcelServiceServer)
	serverServer := server.NewServer(serverConfig, grpcServer)
	return serverServer, nil
}

// wire.go:

func ProvideGrpcServer(parcelService pb.ParcelServiceServer) *grpc.Server {
	s := grpc.NewServer()
	pb.RegisterParcelServiceServer(s, parcelService)
	return s
}
